Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.ssh.insert_key = false
  config.vm.hostname = "uebung"

  config.vm.network "private_network", ip: "192.168.33.10"

end
