---
- name: ensure apt cache is up to date
  apt: update_cache=yes

# - name: install required modules
#   apt:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - nodejs
#     - npm

