---
- name: install postgres dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev # ansible postgres req.
    - python-psycopg2 # ansible postgres req.

- name: create postgres database
  postgresql_db:
    name: "{{app_database_name}}"
  become_user: postgres

- name: create postgres user
  postgresql_user:
    db: "{{app_database_name}}"
    name: "{{app_database_username}}"
    priv: ALL
    password: "{{postgres_app_password}}"
  become_user: postgres
